using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class UIManager : MonoBehaviour
{
    [SerializeField] private List<GameObject> openPopups = new List<GameObject>();

    [SerializeField] private GameObject statWindow;
    [SerializeField] private GameObject pauseWindow;

    void Update()
    {
        //퀢쮱칙 얳쐑
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (openPopups.Count > 0)
                CloseLastOpenedPopup();
            else
                OpenPopup(pauseWindow);
        }

        //칭첇쮩 촋줮 찘썴 얳쐑
        if (Input.GetKey(KeyCode.Tab))
        {
            SetUIActive(statWindow, true);
        }
        else if(Input.GetKeyUp(KeyCode.Tab))
        {
            SetUIActive(statWindow, false);
        }
    }

    //UI퀢쮱칙 찘쐑
    public void OpenPopup(GameObject popup) 
    {
        if(popup != null)
        {
            SetUIActive(popup, true);
            openPopups.Add(popup);
        }
    }

    //UI퀢쮱칙 얳쐑
    public void ClosePopup(GameObject popup)
    {
        if(popup != null && openPopups.Contains(popup))
        {
            SetUIActive(popup, false);
            openPopups.Remove(popup);
        }
    }

    //쌰천 쐋찌 찘쟗 퀢쮱칙 얳쐑
    public void CloseLastOpenedPopup()
    {
        if(openPopups.Count > 0)
        {
            ClosePopup(openPopups.Last());
        }
    }

    //젏왢 퀢쮱칙 얳쐑
    public void CloseAllOpenPopups()
    {
        while (openPopups.Count > 0)
        {
            ClosePopup(openPopups.Last());
        }
    }

    //UI Active 쨥촋
    public void SetUIActive(GameObject uiObject, bool isActive)
    {
        if (uiObject != null)
        {
            uiObject.SetActive(isActive);
        }
    }
}
